[build]
  base = "client"
  command = "npm run build"
  publish = "client/dist"

[functions]
  directory = "client/netlify/functions"
  external_node_modules = [
    "module-one",
    "module-two"
  ]
